name: Tests

on: push

jobs:
  lint:
    name: Run tests
    runs-on: ubuntu-latest
    container: "node:12-alpine"
    steps:
      - uses: actions/checkout@v2
      - run: npm install --frozen-lockfile
      - run: yarn test
